// <auto-generated />
using System;
using DA.NA.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DA.NA.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320203923_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DA.NA.Core.Entities.AssessmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("AssessmentItems");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.ItemType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DefaultUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrapiId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefaultUnitId");

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.NeedsAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SupersedesId");

                    b.ToTable("NeedsAssessments");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HubOfOrgId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastSubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SalesforceId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HubOfOrgId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrgId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.StalenessResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NewAssessmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NotificationSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentItemId");

                    b.HasIndex("NewAssessmentId");

                    b.ToTable("StalenessResponses");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ToBaseFactor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrgId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.AssessmentItem", b =>
                {
                    b.HasOne("DA.NA.Core.Entities.NeedsAssessment", "Assessment")
                        .WithMany("Items")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DA.NA.Core.Entities.ItemType", "ItemType")
                        .WithMany("AssessmentItems")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DA.NA.Core.Entities.Unit", "Unit")
                        .WithMany("AssessmentItems")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("ItemType");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.ItemType", b =>
                {
                    b.HasOne("DA.NA.Core.Entities.Unit", "DefaultUnit")
                        .WithMany("ItemTypes")
                        .HasForeignKey("DefaultUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultUnit");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.NeedsAssessment", b =>
                {
                    b.HasOne("DA.NA.Core.Entities.Project", "Project")
                        .WithMany("Assessments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DA.NA.Core.Entities.NeedsAssessment", "Supersedes")
                        .WithMany()
                        .HasForeignKey("SupersedesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Project");

                    b.Navigation("Supersedes");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.Organisation", b =>
                {
                    b.HasOne("DA.NA.Core.Entities.Organisation", "HubOfOrg")
                        .WithMany()
                        .HasForeignKey("HubOfOrgId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HubOfOrg");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.Project", b =>
                {
                    b.HasOne("DA.NA.Core.Entities.Organisation", "Org")
                        .WithMany("Projects")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Org");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.StalenessResponse", b =>
                {
                    b.HasOne("DA.NA.Core.Entities.AssessmentItem", "AssessmentItem")
                        .WithMany("StalenessResponses")
                        .HasForeignKey("AssessmentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DA.NA.Core.Entities.NeedsAssessment", "NewAssessment")
                        .WithMany()
                        .HasForeignKey("NewAssessmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssessmentItem");

                    b.Navigation("NewAssessment");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.User", b =>
                {
                    b.HasOne("DA.NA.Core.Entities.Organisation", "Org")
                        .WithMany("Users")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Org");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.AssessmentItem", b =>
                {
                    b.Navigation("StalenessResponses");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.ItemType", b =>
                {
                    b.Navigation("AssessmentItems");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.NeedsAssessment", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.Organisation", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.Project", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("DA.NA.Core.Entities.Unit", b =>
                {
                    b.Navigation("AssessmentItems");

                    b.Navigation("ItemTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
